#!/usr/bin/env bash
# install.sh — SSH Watcher automated installer
# Run as root: sudo bash install.sh
set -euo pipefail

# ── Colours ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()    { echo -e "${CYAN}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
die()     { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

# ── Root check ────────────────────────────────────────────────────────────────
[[ $EUID -eq 0 ]] || die "Run as root: sudo bash install.sh"

INSTALL_DIR="/opt/ssh_watcher"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo ""
echo "════════════════════════════════════════════════════"
echo "  SSH Watcher — Installer"
echo "════════════════════════════════════════════════════"
echo ""

# ── Step 1: System packages ───────────────────────────────────────────────────
info "Step 1/9: Installing system packages..."
apt-get update -q
apt-get install -y -q nmap python3 python3-venv python3-pip git sqlite3 ufw \
                      apt-transport-https software-properties-common wget curl
success "System packages installed."

# ── Step 2: Grafana ───────────────────────────────────────────────────────────
info "Step 2/9: Installing Grafana..."
if ! dpkg -l grafana &>/dev/null; then
    wget -q -O /tmp/grafana.gpg https://apt.grafana.com/gpg.key
    gpg --dearmor < /tmp/grafana.gpg > /usr/share/keyrings/grafana.gpg
    echo "deb [signed-by=/usr/share/keyrings/grafana.gpg] https://apt.grafana.com stable main" \
        > /etc/apt/sources.list.d/grafana.list
    apt-get update -q
    apt-get install -y -q grafana
    success "Grafana installed."
else
    success "Grafana already installed — skipping."
fi

# ── Step 3: Infinity plugin ───────────────────────────────────────────────────
info "Step 3/9: Installing Infinity datasource plugin..."
if [[ ! -d /var/lib/grafana/plugins/yesoreyeram-infinity-datasource ]]; then
    grafana-cli --pluginsDir /var/lib/grafana/plugins plugins install yesoreyeram-infinity-datasource
    success "Infinity plugin installed."
else
    success "Infinity plugin already present — skipping."
fi

# ── Step 4: API keys ──────────────────────────────────────────────────────────
info "Step 4/9: API key configuration..."

CONFIG_FILE="$INSTALL_DIR/config.py"

if [[ -f "$CONFIG_FILE" ]]; then
    warn "config.py already exists — skipping key prompts. Edit manually if needed."
else
    echo ""
    echo "  Enter your API keys (press Enter to skip any — watcher still works, enrichment limited):"
    echo ""
    read -rp "  VirusTotal API key  : " VT_KEY
    read -rp "  Shodan API key      : " SHODAN_KEY_VAL
    read -rp "  AbuseIPDB API key   : " ABUSE_KEY
    read -rp "  GreyNoise API key   : " GN_KEY
    echo ""

    cat > "$CONFIG_FILE" << PYEOF
# config.py — generated by install.sh
AUTH_LOG      = "/var/log/auth.log"
DB_PATH       = "/opt/ssh_watcher/watcher.db"
LOG_FILE      = "/opt/ssh_watcher/watcher.log"
VT_API_KEY    = "${VT_KEY}"
SHODAN_KEY    = "${SHODAN_KEY_VAL}"
ABUSEIPDB_KEY = "${ABUSE_KEY}"
GREYNOISE_KEY = "${GN_KEY}"
RESCAN_HRS    = 24
WORKERS       = 3
NMAP_TIMEOUT  = 120
API_PORT      = 8888
PYEOF
    success "config.py written."
fi

# ── Step 5: Python venv ───────────────────────────────────────────────────────
info "Step 5/9: Setting up Python virtual environment..."
if [[ ! -d "$INSTALL_DIR/venv" ]]; then
    python3 -m venv "$INSTALL_DIR/venv"
fi
"$INSTALL_DIR/venv/bin/pip" install --quiet flask shodan requests
success "Python environment ready."

# ── Step 6: Database ──────────────────────────────────────────────────────────
info "Step 6/9: Initialising database..."
python3 "$INSTALL_DIR/setup_db.py"
success "Database ready."

# ── Step 7: Grafana configuration ─────────────────────────────────────────────
info "Step 7/9: Configuring Grafana..."

GRAFANA_INI="/etc/grafana/grafana.ini"

# Patch grafana.ini sections (idempotent)
patch_ini() {
    local section="$1" key="$2" value="$3"
    if grep -q "^${key} = " "$GRAFANA_INI"; then
        sed -i "s|^${key} = .*|${key} = ${value}|" "$GRAFANA_INI"
    elif grep -q "^\[${section}\]" "$GRAFANA_INI"; then
        sed -i "/^\[${section}\]/a ${key} = ${value}" "$GRAFANA_INI"
    else
        echo -e "\n[${section}]\n${key} = ${value}" >> "$GRAFANA_INI"
    fi
}

# Disable new k8s query API (dashboard panels need legacy path)
patch_ini "feature_toggles" "grafanaAPIServerWithExperimentalAPIs" "false"
# Allow Infinity plugin to query localhost
patch_ini "plugin.yesoreyeram-infinity-datasource" "allow_local_mode" "true"
# Enable anonymous viewer access (safe when UFW-restricted)
patch_ini "auth.anonymous" "enabled" "true"
patch_ini "auth.anonymous" "org_role" "Editor"

systemctl enable --now grafana-server
sleep 5  # wait for Grafana to start

success "Grafana configured."

# ── Step 8: Systemd services ──────────────────────────────────────────────────
info "Step 8/9: Installing systemd services..."

cp "$INSTALL_DIR/ssh_watcher.service"     /etc/systemd/system/
cp "$INSTALL_DIR/ssh_watcher_api.service" /etc/systemd/system/

systemctl daemon-reload
systemctl enable --now ssh_watcher
systemctl enable --now ssh_watcher_api

sleep 3
systemctl is-active ssh_watcher     && success "ssh_watcher service running." \
                                    || warn    "ssh_watcher failed to start — check: journalctl -u ssh_watcher"
systemctl is-active ssh_watcher_api && success "ssh_watcher_api service running." \
                                    || warn    "ssh_watcher_api failed to start — check: journalctl -u ssh_watcher_api"

# ── Step 9: Grafana datasource + dashboard ────────────────────────────────────
info "Step 9/9: Creating Grafana datasource and importing dashboard..."

# Wait for API
RETRIES=10
until curl -sf -u admin:admin http://localhost:3000/api/health &>/dev/null || [[ $RETRIES -eq 0 ]]; do
    sleep 2; ((RETRIES--))
done

# Create datasource (ignore error if already exists)
curl -sf -u admin:admin -X POST http://localhost:3000/api/datasources \
  -H "Content-Type: application/json" \
  -d '{
    "name":"SSH Watcher API",
    "type":"yesoreyeram-infinity-datasource",
    "uid":"ssh-watcher-api",
    "access":"proxy",
    "url":"",
    "jsonData":{"baseUrl":"http://localhost:8888","allowedHosts":["http://localhost:8888"]}
  }' &>/dev/null && success "Datasource created." || warn "Datasource may already exist — continuing."

# Import dashboard
if [[ -f "$INSTALL_DIR/dashboard.json" ]]; then
    DASHBOARD=$(cat "$INSTALL_DIR/dashboard.json")
    HTTP=$(curl -sf -o /dev/null -w "%{http_code}" -u admin:admin \
      -X POST http://localhost:3000/api/dashboards/db \
      -H "Content-Type: application/json" \
      -d "{\"dashboard\": $DASHBOARD, \"overwrite\": true}")
    [[ "$HTTP" == "200" ]] && success "Dashboard imported." \
                           || warn "Dashboard import returned HTTP $HTTP — import manually via Grafana UI."
fi

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo "════════════════════════════════════════════════════"
echo -e "  ${GREEN}Installation complete!${NC}"
echo "════════════════════════════════════════════════════"
echo ""
SERVER_IP=$(curl -sf https://api.ipify.org 2>/dev/null || hostname -I | awk '{print $1}')
echo "  Dashboard : http://${SERVER_IP}:3000/d/ssh-watcher-v3/ssh-watcher"
echo "  REST API  : http://localhost:8888/api/summary"
echo "  Logs      : tail -f /opt/ssh_watcher/watcher.log"
echo ""
echo "  Next steps:"
echo "  1. Open each Grafana panel → Edit → Apply/Save to activate queries"
echo "     (Grafana 13 requires this one-time step after dashboard import)"
echo "  2. Add firewall rule: sudo ufw allow from YOUR_IP to any port 3000 proto tcp"
echo "  3. Update your cloud security group: TCP 3000 inbound from YOUR_IP"
echo "  4. Run backfill for existing IPs:"
echo "     sudo $INSTALL_DIR/venv/bin/python $INSTALL_DIR/backfill.py"
echo "     sudo $INSTALL_DIR/venv/bin/python $INSTALL_DIR/backfill_enrich.py"
echo "     sudo $INSTALL_DIR/venv/bin/python $INSTALL_DIR/assess.py"
echo ""
